[package]
name = "mijia"
version = "0.2.0"
authors = ["Luis Félix <lcs.felix@gmail.com>", "Andrew Walbran <qwandor@google.com>", "David Laban <alsuren@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "A library for connecting to Xiaomi Mijia 2 Bluetooth temperature/humidity sensors."
repository = "https://github.com/alsuren/mijia-homie/"
keywords = ["blue", "bluetooth"]
categories = ["hardware-support"]

[dependencies]
bluez-generated = { version = "0.2.0", path = "../bluez-generated" }
dbus = { version = "0.9.0", features = ["futures"] }
dbus-tokio = "0.6.0"
futures = "0.3.8"
itertools = "0.10.0"
log = "0.4.11"
serde = "1.0.118"
serde_derive = "1.0.118"
serde-xml-rs = "0.4.0"
thiserror = "1.0.22"
tokio = "0.3.6"
tokio-compat-02 = "0.1.2"
uuid = "0.8.1"

[dev-dependencies]
chrono = "0.4.19"
eyre = "0.6.3"
pretty_env_logger = "0.4.0"
tokio = { version = "0.3.6", features = ["macros", "rt", "rt-multi-thread", "time"] }
